# Generated by Django 4.2 on 2023-05-01 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kastrat',
            name='field_of_work',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('AIR_CONDITIONER', 'Air Conditioner'), ('ALL_IN_ONE', 'All in One'), ('CARPENTRY', 'Carpentry'), ('ELECTRICITY', 'Electricity'), ('GARDENING', 'Gardening'), ('HOME_MACHINES', 'Home Machines'), ('HOUSEKEEPING', 'Housekeeping'), ('INTERIOR_DESIGN', 'Interior Design'), ('LOCKS', 'Locks'), ('PAINTING', 'Painting'), ('PLUMBING', 'Plumbing'), ('WATER_HEATERS', 'Water Heaters')], default='CUSTOMER', max_length=50),
        ),
        migrations.AlterField(
            model_name='kastrat',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
