# Generated by Django 4.2 on 2023-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kastrat',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
