# Generated by Django 4.2 on 2023-05-01 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_kastrat_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kastrat',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 8, 16, 40, 742233, tzinfo=datetime.timezone.utc)),
        ),
    ]
