# Generated by Django 4.2 on 2023-05-01 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_kastrat_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kastrat',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
