# Generated by Django 4.2 on 2023-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
