# Generated by Django 4.2 on 2023-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='address',
            field=models.TextField(max_length=300),
        ),
    ]
